#!/usr/bin/env python3
"""Generate a synthetic, TPC-H-*derived* `lineitem`/`part`/`partsupp`/`orders`/`customer`/`nation`/`supplier`/`region` set as Parquet.

**This is not the official TPC-H `dbgen` tool and does not produce
certified TPC-H data.** It generates all eight non-`lineitem` and
`lineitem` tables TPC-H defines (`lineitem`, `part`, `partsupp`, `orders`,
`customer`, `nation`, `supplier`, `region`) with TPC-H's column
names/types (decimal columns as DOUBLE -- see "Deviations" below) and
roughly TPC-H-shaped value distributions, sized approximately like real
TPC-H at the requested scale factor. This is sufficient for every query
KernelLake currently supports (Q6, Q1 -- single-table scans over
`lineitem`; Q19/Q14 -- a two-table `lineitem`/`part` join; Q12 -- a
two-table `orders`/`lineitem` join; Q3 -- a three-table `customer`/
`orders`/`lineitem` join; Q10 -- a four-table `customer`/`orders`/
`lineitem`/`nation` join; Q5 -- a six-table `customer`/`orders`/
`lineitem`/`supplier`/`nation`/`region` join; Q7 -- a six-table
`supplier`/`lineitem`/`orders`/`customer`/`nation`/`nation` join,
`nation` joined twice under different aliases; Q9 -- a six-table
`part`/`supplier`/`lineitem`/`partsupp`/`orders`/`nation` join), but must
never be described or published as an official TPC-H benchmark dataset.

Deviations from canonical TPC-H, documented per the spec's requirement to
record every one:
  - `l_suppkey` is **not** drawn independently of `l_partkey`. Real
    TPC-H's own `partsupp` table means every part is stocked by exactly
    `PARTSUPP_SUPPLIERS_PER_PART` (4) suppliers, and Q9 joins `lineitem`
    to `partsupp` on *both* `ps_partkey = l_partkey` and `ps_suppkey =
    l_suppkey` together -- an independently-random `l_suppkey` (this
    generator's own behavior before Q9 was added) would essentially never
    match a real `partsupp` row for that part. `suppliers_for_part()` is
    the deterministic (not dbgen's own selection formula, but the same
    shape) function both `generate_lineitem_batch()`'s `l_suppkey` draw
    and `generate_partsupp_table()`'s own rows are built from, so they
    always agree. This is the one foreign key in this generator that
    isn't independently sampled -- every other one still is.
  - `nation`/`region` use real TPC-H `dbgen` reference data (all 25
    nations'/5 regions' names and keys, verbatim -- unlike every other
    table's rows, which are independently sampled, not reproduced from
    `dbgen`) since they're small, fixed lookup tables where hardcoding
    the real values is simpler than inventing synthetic ones, the same
    rationale already applied to `MKTSEGMENTS`/`ORDER_PRIORITIES`/
    `SHIP_MODES` below.
  - l_quantity/l_extendedprice/l_discount/l_tax/p_retailprice/
    o_totalprice/c_acctbal are DOUBLE, not DECIMAL. KernelLake's GPU
    execution layer does support DECIMAL now (see docs/ARCHITECTURE.md's
    "DECIMAL support"), so this is a generator choice, not an engine
    limitation -- switching would require regenerating and re-validating
    every existing TPC-H fixture, which hasn't been done.
  - Row content (prices, dates, flags, brands, containers, priorities,
    market segments) is independently sampled per row from
    TPC-H-plausible ranges/value sets, not generated by the reference
    `dbgen` algorithm -- so exact row values, and therefore exact query
    results, will differ from official TPC-H data at the same scale
    factor. Only the schema and approximate row count follow the TPC-H SF
    convention (`part` scales directly with SF, per TPC-H's own
    convention, unlike `lineitem`'s order-count-derived scaling -- see
    `PART_ROWS_PER_SF`; `orders` has exactly one row per distinct
    `l_orderkey` `lineitem` generated, per TPC-H's own 1:N orders:lineitem
    relationship; `customer`/`supplier` are each a fixed `CUSTOMER_ROWS`/
    `SUPPLIER_ROWS` regardless of SF, matching `orders`' own fixed
    `o_custkey` range and `lineitem`'s own fixed `l_suppkey` range -- see
    below).
  - `l_partkey` is drawn uniformly from `[1, total_part_rows]`,
    `l_suppkey` from a fixed `[1, SUPPLIER_ROWS]`, and `o_custkey`/
    `c_custkey` both use a fixed `[1, CUSTOMER_ROWS]` range regardless of
    scale factor (real TPC-H's `customer`/`supplier` counts scale with
    SF; this generator's don't) -- none is generated by dbgen's actual
    selection distribution, but all are sufficient for every join in
    their row range to find a real matching row (no dangling foreign
    keys), which is what actually matters for validating query
    correctness.

Usage:
    python3 tools/generate_tpch.py --scale-factor 1 --output /tmp/kernellake-tpch-sf1 \
        --format parquet --compression zstd --row-group-rows 1000000
"""

import argparse
import datetime
import json
import random
import sys
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

# Real TPC-H's lineitem row count is approximately 6,000,000 * scale factor
# (~4 line items per order, 1,500,000 * SF orders).
LINEITEM_ROWS_PER_SF = 6_000_000

# Real TPC-H's part row count scales directly with SF (unlike lineitem's
# order-count-derived scaling above).
PART_ROWS_PER_SF = 200_000

# generate_orders_batch materializes one batch's rows as Python lists before
# handing them to Arrow -- unbounded batch size means unbounded memory (this
# OOM-killed a full SF1000 run, which has ~1.5B orders rows, after 127GB
# RSS). Batch it the same way the --files loop already batches lineitem.
ORDERS_BATCH_ROWS = 5_000_000

# A representative subset of TPC-H's own p_container domain (dbgen draws
# from a larger cross product of size/container-type words) -- covers every
# size class Q19 filters on (SM/MED/LG).
CONTAINERS = [
    "SM CASE", "SM BOX", "SM PACK", "SM PKG",
    "MED BAG", "MED BOX", "MED PKG", "MED PACK",
    "LG CASE", "LG BOX", "LG PACK", "LG PKG",
]

# TPC-H's p_brand values are "Brand#" + one digit each from two
# manufacturer/brand ranges (1-5 x 1-5 -- 25 total combinations).
BRANDS = [f"Brand#{m}{b}" for m in range(1, 6) for b in range(1, 6)]

PART_TYPES = [
    "STANDARD ANODIZED TIN", "SMALL PLATED COPPER", "LARGE BRUSHED STEEL",
    "MEDIUM POLISHED BRASS", "PROMO BURNISHED NICKEL", "ECONOMY ANODIZED STEEL",
]

# A representative subset of real TPC-H dbgen's own ~92-word p_name color
# list (dbgen builds p_name as 5 of these, space-joined, drawn without
# replacement) -- includes "green" specifically because Q9's WHERE clause
# filters `p_name LIKE '%green%'`; a purely synthetic name (e.g.
# "synthetic-part-{k}", this generator's own choice before Q9 was added)
# would never match that filter at all, making Q9 trivially return zero
# rows regardless of whether the query itself is correct.
P_NAME_WORDS = [
    "almond", "antique", "aquamarine", "azure", "beige", "bisque", "black",
    "blue", "blush", "brown", "burlywood", "burnished", "chartreuse",
    "chocolate", "coral", "cornflower", "cornsilk", "cream", "cyan", "dark",
    "deep", "dim", "drab", "firebrick", "floral", "forest", "frosted",
    "goldenrod", "green", "grey", "honeydew", "hot", "indian", "ivory",
    "khaki", "lavender", "lawn", "lemon", "light", "lime", "linen",
    "magenta", "maroon", "medium", "metallic", "midnight", "mint", "misty",
    "moccasin", "navy", "olive", "orange", "orchid", "pale", "papaya",
    "peach", "peru", "pink", "plum", "powder", "puff", "purple", "red",
    "rose", "rosy", "royal", "saddle", "salmon", "sandy", "seashell",
    "sienna", "sky", "slate", "smoke", "snow", "spring", "steel", "tan",
    "thistle", "tomato", "turquoise", "violet", "wheat", "white", "yellow",
]

# TPC-H's own 5 o_orderpriority values, verbatim (Q12's WHERE/CASE branches
# match these exact strings).
ORDER_PRIORITIES = ["1-URGENT", "2-HIGH", "3-MEDIUM", "4-NOT SPECIFIED", "5-LOW"]
ORDER_STATUSES = ["O", "F", "P"]

# Fixed regardless of scale factor, matching generate_orders_batch's own
# o_custkey range (also fixed at 150,000 -- a pre-existing simplification,
# not scaled by SF the way real TPC-H's customer count would be) -- every
# o_custkey value has a real customer row to join against, no dangling
# foreign keys.
CUSTOMER_ROWS = 150_000

# Fixed regardless of scale factor, matching generate_lineitem_batch's own
# l_suppkey range (rng.randint(1, 10_000), a pre-existing simplification
# predating this constant's own introduction -- not scaled by SF the way
# real TPC-H's supplier count would be) -- every l_suppkey value has a
# real supplier row to join against, no dangling foreign keys.
SUPPLIER_ROWS = 10_000

# TPC-H's own 5 c_mktsegment values, verbatim (Q3's WHERE clause matches
# this exact string).
MKTSEGMENTS = ["BUILDING", "AUTOMOBILE", "MACHINERY", "HOUSEHOLD", "FURNITURE"]

# TPC-H's canonical order-date range is 1992-01-01 through 1998-08-02;
# ship/commit/receipt dates extend a little past that. CURRENT_DATE below
# matches dbgen's reference "current date" (1998-12-01), used for the
# returnflag/linestatus threshold (see module docstring: this threshold
# logic is an approximation of dbgen's, not a reproduction of it).
MIN_ORDER_DATE = datetime.date(1992, 1, 1)
CURRENT_DATE = datetime.date(1998, 12, 1)
RETURNFLAG_THRESHOLD = CURRENT_DATE - datetime.timedelta(days=90)

SHIP_INSTRUCTS = ["DELIVER IN PERSON", "COLLECT COD", "NONE", "TAKE BACK RETURN"]
SHIP_MODES = ["REG AIR", "AIR", "RAIL", "SHIP", "TRUCK", "MAIL", "FOB"]

# Real TPC-H dbgen nation.tbl, verbatim: (n_nationkey, n_name, n_regionkey).
# c_nationkey above is drawn from randint(0, 24), so this must cover exactly
# nationkeys 0-24 for every customer row to have a real nation to join
# against (same no-dangling-foreign-key rationale as CUSTOMER_ROWS).
NATIONS = [
    (0, "ALGERIA", 0), (1, "ARGENTINA", 1), (2, "BRAZIL", 1), (3, "CANADA", 1),
    (4, "EGYPT", 4), (5, "ETHIOPIA", 0), (6, "FRANCE", 3), (7, "GERMANY", 3),
    (8, "INDIA", 2), (9, "INDONESIA", 2), (10, "IRAN", 4), (11, "IRAQ", 4),
    (12, "JAPAN", 2), (13, "JORDAN", 4), (14, "KENYA", 0), (15, "MOROCCO", 0),
    (16, "MOZAMBIQUE", 0), (17, "PERU", 1), (18, "CHINA", 2), (19, "ROMANIA", 3),
    (20, "SAUDI ARABIA", 4), (21, "VIETNAM", 2), (22, "RUSSIA", 3),
    (23, "UNITED KINGDOM", 3), (24, "UNITED STATES", 1),
]

# Real TPC-H dbgen region.tbl, verbatim: (r_regionkey, r_name). Every
# n_regionkey value in NATIONS above (0-4) has a matching row here, no
# dangling foreign keys -- same rationale as NATIONS' own comment.
REGIONS = [
    (0, "AFRICA"), (1, "AMERICA"), (2, "ASIA"), (3, "EUROPE"), (4, "MIDDLE EAST"),
]

# Real TPC-H's own fixed count: every part is stocked by exactly 4
# suppliers (dbgen's own PS_SUPP_CNT), regardless of scale factor.
PARTSUPP_SUPPLIERS_PER_PART = 4


def suppliers_for_part(partkey: int, supplier_rows: int) -> list[int]:
    """The PARTSUPP_SUPPLIERS_PER_PART supplier IDs (1-indexed) that stock
    `partkey` -- a deterministic function of partkey alone, not dbgen's
    own selection formula (real dbgen: ((p - 1 + i * (S / 4 + (p - 1) /
    S)) mod S) + 1 for i in 0..3), but the same *shape*: a small, fixed,
    reproducible set per part. This is the join key `generate_partsupp_
    table()`'s own rows and `generate_lineitem_batch()`'s own l_suppkey
    selection must agree on -- unlike every other foreign key in this
    generator (drawn independently uniformly at random), l_suppkey can't
    be independent of l_partkey here: TPC-H Q9 joins lineitem to partsupp
    on *both* ps_partkey = l_partkey and ps_suppkey = l_suppkey together
    (partsupp's own primary key is the pair), so an l_suppkey drawn
    independently of l_partkey would almost never match any real partsupp
    row for that part. `supplier_rows` (SUPPLIER_ROWS, always >> 4) makes
    every returned ID distinct with no explicit uniqueness check needed.
    """
    base = ((partkey - 1) * PARTSUPP_SUPPLIERS_PER_PART) % supplier_rows
    return [(base + i) % supplier_rows + 1 for i in range(PARTSUPP_SUPPLIERS_PER_PART)]


def epoch_days(date: datetime.date) -> int:
    return (date - datetime.date(1970, 1, 1)).days


def generate_lineitem_batch(
    rng: random.Random, row_count: int, first_orderkey: int, total_part_rows: int
) -> pa.Table:
    orderkey = []
    partkey = []
    suppkey = []
    linenumber = []
    quantity = []
    extendedprice = []
    discount = []
    tax = []
    returnflag = []
    linestatus = []
    shipdate = []
    commitdate = []
    receiptdate = []
    shipinstruct = []
    shipmode = []
    comment = []

    current_orderkey = first_orderkey
    line_in_order = 0
    lines_for_this_order = rng.randint(1, 7)

    for _ in range(row_count):
        if line_in_order >= lines_for_this_order:
            current_orderkey += 1
            line_in_order = 0
            lines_for_this_order = rng.randint(1, 7)
        line_in_order += 1

        order_date = MIN_ORDER_DATE + datetime.timedelta(
            days=rng.randint(0, (CURRENT_DATE - MIN_ORDER_DATE).days - 151)
        )
        ship = order_date + datetime.timedelta(days=rng.randint(1, 121))
        commit = order_date + datetime.timedelta(days=rng.randint(30, 90))
        receipt = ship + datetime.timedelta(days=rng.randint(1, 30))

        qty = rng.randint(1, 50)
        unit_price = rng.uniform(1.00, 2000.00)
        line_extended = round(qty * unit_price, 2)

        if receipt <= RETURNFLAG_THRESHOLD:
            flag = rng.choice(["R", "A"])
        else:
            flag = "N"
        status = "O" if ship > RETURNFLAG_THRESHOLD else "F"

        this_partkey = rng.randint(1, total_part_rows)
        orderkey.append(current_orderkey)
        partkey.append(this_partkey)
        # One of this part's own PARTSUPP_SUPPLIERS_PER_PART suppliers
        # (see suppliers_for_part()'s own comment) -- not an independent
        # rng.randint(1, SUPPLIER_ROWS) draw, so every lineitem row's
        # (l_partkey, l_suppkey) pair always has a real matching partsupp
        # row (TPC-H Q9's join needs exactly this).
        suppkey.append(rng.choice(suppliers_for_part(this_partkey, SUPPLIER_ROWS)))
        linenumber.append(line_in_order)
        quantity.append(float(qty))
        extendedprice.append(line_extended)
        discount.append(round(rng.uniform(0.0, 0.10), 2))
        tax.append(round(rng.uniform(0.0, 0.08), 2))
        returnflag.append(flag)
        linestatus.append(status)
        shipdate.append(epoch_days(ship))
        commitdate.append(epoch_days(commit))
        receiptdate.append(epoch_days(receipt))
        shipinstruct.append(rng.choice(SHIP_INSTRUCTS))
        shipmode.append(rng.choice(SHIP_MODES))
        comment.append("synthetic-tpch-lineitem-comment")

    schema = pa.schema(
        [
            pa.field("l_orderkey", pa.int64(), False),
            pa.field("l_partkey", pa.int64(), False),
            pa.field("l_suppkey", pa.int64(), False),
            pa.field("l_linenumber", pa.int32(), False),
            pa.field("l_quantity", pa.float64(), False),
            pa.field("l_extendedprice", pa.float64(), False),
            pa.field("l_discount", pa.float64(), False),
            pa.field("l_tax", pa.float64(), False),
            pa.field("l_returnflag", pa.utf8(), False),
            pa.field("l_linestatus", pa.utf8(), False),
            pa.field("l_shipdate", pa.date32(), False),
            pa.field("l_commitdate", pa.date32(), False),
            pa.field("l_receiptdate", pa.date32(), False),
            pa.field("l_shipinstruct", pa.utf8(), False),
            pa.field("l_shipmode", pa.utf8(), False),
            pa.field("l_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "l_orderkey": orderkey,
            "l_partkey": partkey,
            "l_suppkey": suppkey,
            "l_linenumber": linenumber,
            "l_quantity": quantity,
            "l_extendedprice": extendedprice,
            "l_discount": discount,
            "l_tax": tax,
            "l_returnflag": returnflag,
            "l_linestatus": linestatus,
            "l_shipdate": shipdate,
            "l_commitdate": commitdate,
            "l_receiptdate": receiptdate,
            "l_shipinstruct": shipinstruct,
            "l_shipmode": shipmode,
            "l_comment": comment,
        },
        schema=schema,
    )


def generate_part_table(rng: random.Random, row_count: int) -> pa.Table:
    partkey = list(range(1, row_count + 1))
    name = [" ".join(rng.sample(P_NAME_WORDS, 5)) for _ in partkey]
    mfgr = [f"Manufacturer#{(k % 5) + 1}" for k in partkey]
    brand = [rng.choice(BRANDS) for _ in partkey]
    ptype = [rng.choice(PART_TYPES) for _ in partkey]
    size = [rng.randint(1, 50) for _ in partkey]
    container = [rng.choice(CONTAINERS) for _ in partkey]
    retailprice = [round(rng.uniform(900.0, 2100.0), 2) for _ in partkey]
    comment = ["synthetic-tpch-part-comment" for _ in partkey]

    schema = pa.schema(
        [
            pa.field("p_partkey", pa.int64(), False),
            pa.field("p_name", pa.utf8(), False),
            pa.field("p_mfgr", pa.utf8(), False),
            pa.field("p_brand", pa.utf8(), False),
            pa.field("p_type", pa.utf8(), False),
            pa.field("p_size", pa.int32(), False),
            pa.field("p_container", pa.utf8(), False),
            pa.field("p_retailprice", pa.float64(), False),
            pa.field("p_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "p_partkey": partkey,
            "p_name": name,
            "p_mfgr": mfgr,
            "p_brand": brand,
            "p_type": ptype,
            "p_size": size,
            "p_container": container,
            "p_retailprice": retailprice,
            "p_comment": comment,
        },
        schema=schema,
    )


def generate_orders_batch(rng: random.Random, first_orderkey: int, row_count: int) -> pa.Table:
    # One row per distinct l_orderkey generate_lineitem_batch produced --
    # TPC-H's own 1:N orders:lineitem relationship -- so every lineitem row
    # has a real order to join against (no dangling foreign keys), same
    # rationale as generate_part_table's l_partkey range. Batched (see
    # ORDERS_BATCH_ROWS) rather than building all of `orders` at once, since
    # at large scale factors max_orderkey is itself in the billions.
    orderkey = list(range(first_orderkey, first_orderkey + row_count))
    custkey = [rng.randint(1, 150_000) for _ in orderkey]
    orderstatus = [rng.choice(ORDER_STATUSES) for _ in orderkey]
    totalprice = [round(rng.uniform(1000.0, 500_000.0), 2) for _ in orderkey]
    orderdate = [
        epoch_days(MIN_ORDER_DATE + datetime.timedelta(days=rng.randint(0, (CURRENT_DATE - MIN_ORDER_DATE).days)))
        for _ in orderkey
    ]
    orderpriority = [rng.choice(ORDER_PRIORITIES) for _ in orderkey]
    clerk = [f"Clerk#{rng.randint(1, 1000):09d}" for _ in orderkey]
    shippriority = [0 for _ in orderkey]
    comment = ["synthetic-tpch-orders-comment" for _ in orderkey]

    schema = pa.schema(
        [
            pa.field("o_orderkey", pa.int64(), False),
            pa.field("o_custkey", pa.int64(), False),
            pa.field("o_orderstatus", pa.utf8(), False),
            pa.field("o_totalprice", pa.float64(), False),
            pa.field("o_orderdate", pa.date32(), False),
            pa.field("o_orderpriority", pa.utf8(), False),
            pa.field("o_clerk", pa.utf8(), False),
            pa.field("o_shippriority", pa.int32(), False),
            pa.field("o_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "o_orderkey": orderkey,
            "o_custkey": custkey,
            "o_orderstatus": orderstatus,
            "o_totalprice": totalprice,
            "o_orderdate": orderdate,
            "o_orderpriority": orderpriority,
            "o_clerk": clerk,
            "o_shippriority": shippriority,
            "o_comment": comment,
        },
        schema=schema,
    )


def generate_customer_table(rng: random.Random, row_count: int) -> pa.Table:
    custkey = list(range(1, row_count + 1))
    name = [f"synthetic-customer-{k}" for k in custkey]
    address = [f"{k} Synthetic St" for k in custkey]
    nationkey = [rng.randint(0, 24) for _ in custkey]
    phone = [f"{rng.randint(10, 34)}-{rng.randint(100, 999)}-{rng.randint(100, 999)}-{rng.randint(1000, 9999)}"
             for _ in custkey]
    acctbal = [round(rng.uniform(-999.99, 9999.99), 2) for _ in custkey]
    mktsegment = [rng.choice(MKTSEGMENTS) for _ in custkey]
    comment = ["synthetic-tpch-customer-comment" for _ in custkey]

    schema = pa.schema(
        [
            pa.field("c_custkey", pa.int64(), False),
            pa.field("c_name", pa.utf8(), False),
            pa.field("c_address", pa.utf8(), False),
            pa.field("c_nationkey", pa.int32(), False),
            pa.field("c_phone", pa.utf8(), False),
            pa.field("c_acctbal", pa.float64(), False),
            pa.field("c_mktsegment", pa.utf8(), False),
            pa.field("c_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "c_custkey": custkey,
            "c_name": name,
            "c_address": address,
            "c_nationkey": nationkey,
            "c_phone": phone,
            "c_acctbal": acctbal,
            "c_mktsegment": mktsegment,
            "c_comment": comment,
        },
        schema=schema,
    )


def generate_nation_table() -> pa.Table:
    nationkey = [n[0] for n in NATIONS]
    name = [n[1] for n in NATIONS]
    regionkey = [n[2] for n in NATIONS]
    comment = ["synthetic-tpch-nation-comment" for _ in NATIONS]

    schema = pa.schema(
        [
            pa.field("n_nationkey", pa.int32(), False),
            pa.field("n_name", pa.utf8(), False),
            pa.field("n_regionkey", pa.int32(), False),
            pa.field("n_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "n_nationkey": nationkey,
            "n_name": name,
            "n_regionkey": regionkey,
            "n_comment": comment,
        },
        schema=schema,
    )


def generate_region_table() -> pa.Table:
    regionkey = [r[0] for r in REGIONS]
    name = [r[1] for r in REGIONS]
    comment = ["synthetic-tpch-region-comment" for _ in REGIONS]

    schema = pa.schema(
        [
            pa.field("r_regionkey", pa.int32(), False),
            pa.field("r_name", pa.utf8(), False),
            pa.field("r_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "r_regionkey": regionkey,
            "r_name": name,
            "r_comment": comment,
        },
        schema=schema,
    )


def generate_supplier_table(rng: random.Random, row_count: int) -> pa.Table:
    suppkey = list(range(1, row_count + 1))
    name = [f"synthetic-supplier-{k}" for k in suppkey]
    address = [f"{k} Synthetic Ave" for k in suppkey]
    # [0, 24]: same range NATIONS covers, same no-dangling-foreign-key
    # rationale as generate_customer_table's own c_nationkey.
    nationkey = [rng.randint(0, 24) for _ in suppkey]
    phone = [f"{rng.randint(10, 34)}-{rng.randint(100, 999)}-{rng.randint(100, 999)}-{rng.randint(1000, 9999)}"
             for _ in suppkey]
    acctbal = [round(rng.uniform(-999.99, 9999.99), 2) for _ in suppkey]
    comment = ["synthetic-tpch-supplier-comment" for _ in suppkey]

    schema = pa.schema(
        [
            pa.field("s_suppkey", pa.int64(), False),
            pa.field("s_name", pa.utf8(), False),
            pa.field("s_address", pa.utf8(), False),
            pa.field("s_nationkey", pa.int32(), False),
            pa.field("s_phone", pa.utf8(), False),
            pa.field("s_acctbal", pa.float64(), False),
            pa.field("s_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "s_suppkey": suppkey,
            "s_name": name,
            "s_address": address,
            "s_nationkey": nationkey,
            "s_phone": phone,
            "s_acctbal": acctbal,
            "s_comment": comment,
        },
        schema=schema,
    )


def generate_partsupp_table(rng: random.Random, total_part_rows: int, supplier_rows: int) -> pa.Table:
    # Exactly PARTSUPP_SUPPLIERS_PER_PART rows per part, the same
    # suppliers_for_part() set generate_lineitem_batch() draws l_suppkey
    # from -- see that function's own comment for why this pairing has to
    # be exact, not independently sampled the way every other table here
    # is. total_part_rows * PARTSUPP_SUPPLIERS_PER_PART rows total (e.g.
    # 800,000 at SF1's 200,000 parts), comparable in size to `customer`.
    partkey = []
    suppkey = []
    for p in range(1, total_part_rows + 1):
        for s in suppliers_for_part(p, supplier_rows):
            partkey.append(p)
            suppkey.append(s)
    availqty = [rng.randint(1, 9999) for _ in partkey]
    supplycost = [round(rng.uniform(1.00, 1000.00), 2) for _ in partkey]
    comment = ["synthetic-tpch-partsupp-comment" for _ in partkey]

    schema = pa.schema(
        [
            pa.field("ps_partkey", pa.int64(), False),
            pa.field("ps_suppkey", pa.int64(), False),
            pa.field("ps_availqty", pa.int32(), False),
            pa.field("ps_supplycost", pa.float64(), False),
            pa.field("ps_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "ps_partkey": partkey,
            "ps_suppkey": suppkey,
            "ps_availqty": availqty,
            "ps_supplycost": supplycost,
            "ps_comment": comment,
        },
        schema=schema,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scale-factor", type=float, required=True)
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--format", choices=["parquet"], default="parquet")
    parser.add_argument("--compression", choices=["none", "snappy", "zstd"], default="zstd")
    # zstd only -- PyArrow's own codec default (level 1, favors write speed)
    # differs from libzstd's upstream default (level 3, its standard
    # balanced setting -- what most "zstd default" benchmarks/docs mean).
    # Left unset, PyArrow's level-1 default applies, same as before this
    # flag existed. Confirmed via `pa.Codec('zstd').compression_level == 1`
    # against the pyarrow build this repo pins, not assumed from docs.
    parser.add_argument("--compression-level", type=int, default=None)
    parser.add_argument("--row-group-rows", type=int, default=1_000_000)
    parser.add_argument("--files", type=int, default=1, help="Number of lineitem Parquet files to write")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.scale_factor <= 0:
        parser.error("--scale-factor must be positive")
    if args.files <= 0:
        parser.error("--files must be positive")
    if args.compression_level is not None and args.compression != "zstd":
        parser.error("--compression-level only applies to --compression zstd")

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    total_rows = int(LINEITEM_ROWS_PER_SF * args.scale_factor)
    total_part_rows = max(1, int(PART_ROWS_PER_SF * args.scale_factor))
    rng = random.Random(args.seed)
    compression = None if args.compression == "none" else args.compression
    compression_level = args.compression_level

    part_table = generate_part_table(rng, total_part_rows)
    part_path = output_dir / "part-00000.parquet"
    pq.write_table(
        part_table, part_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {total_part_rows} rows to {part_path}")

    partsupp_table = generate_partsupp_table(rng, total_part_rows, SUPPLIER_ROWS)
    partsupp_path = output_dir / "partsupp-00000.parquet"
    pq.write_table(
        partsupp_table, partsupp_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {partsupp_table.num_rows} rows to {partsupp_path}")

    customer_table = generate_customer_table(rng, CUSTOMER_ROWS)
    customer_path = output_dir / "customer-00000.parquet"
    pq.write_table(
        customer_table, customer_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {CUSTOMER_ROWS} rows to {customer_path}")

    nation_table = generate_nation_table()
    nation_path = output_dir / "nation-00000.parquet"
    pq.write_table(
        nation_table, nation_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {len(NATIONS)} rows to {nation_path}")

    region_table = generate_region_table()
    region_path = output_dir / "region-00000.parquet"
    pq.write_table(
        region_table, region_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {len(REGIONS)} rows to {region_path}")

    supplier_table = generate_supplier_table(rng, SUPPLIER_ROWS)
    supplier_path = output_dir / "supplier-00000.parquet"
    pq.write_table(
        supplier_table, supplier_path, compression=compression,
        compression_level=compression_level, row_group_size=args.row_group_rows,
    )
    print(f"wrote {SUPPLIER_ROWS} rows to {supplier_path}")

    rows_per_file = total_rows // args.files
    extra = total_rows % args.files
    next_orderkey = 1
    file_paths = []
    rows_written = 0

    for file_index in range(args.files):
        rows_this_file = rows_per_file + (1 if file_index < extra else 0)
        if rows_this_file == 0:
            continue
        table = generate_lineitem_batch(rng, rows_this_file, next_orderkey, total_part_rows)
        next_orderkey = table.column("l_orderkey")[-1].as_py() + 1
        file_path = output_dir / f"lineitem-{file_index:05d}.parquet"
        pq.write_table(table, file_path, compression=compression, row_group_size=args.row_group_rows)
        file_paths.append(str(file_path))
        rows_written += rows_this_file
        print(f"wrote {rows_this_file} rows to {file_path}")

    max_orderkey = next_orderkey - 1
    orders_file_paths = []
    orders_written = 0
    next_orders_start = 1
    orders_file_index = 0
    while next_orders_start <= max_orderkey:
        batch_rows = min(ORDERS_BATCH_ROWS, max_orderkey - next_orders_start + 1)
        orders_table = generate_orders_batch(rng, next_orders_start, batch_rows)
        orders_path = output_dir / f"orders-{orders_file_index:05d}.parquet"
        pq.write_table(orders_table, orders_path, compression=compression, row_group_size=args.row_group_rows)
        orders_file_paths.append(str(orders_path))
        orders_written += batch_rows
        print(f"wrote {batch_rows} rows to {orders_path}")
        next_orders_start += batch_rows
        orders_file_index += 1

    manifest = {
        "benchmark": "tpch",
        "unofficial": True,
        "disclaimer": "Unofficial TPC-H-derived benchmark. Not a certified TPC result.",
        "scale_factor": args.scale_factor,
        "format": args.format,
        "compression": args.compression,
        "row_group_rows": args.row_group_rows,
        "seed": args.seed,
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "generator": "tools/generate_tpch.py (synthetic, not dbgen -- see module docstring)",
        "tables": {
            "lineitem": {
                "files": file_paths,
                "rows": rows_written,
            },
            "part": {
                "files": [str(part_path)],
                "rows": total_part_rows,
            },
            "partsupp": {
                "files": [str(partsupp_path)],
                "rows": partsupp_table.num_rows,
            },
            "orders": {
                "files": orders_file_paths,
                "rows": orders_written,
            },
            "customer": {
                "files": [str(customer_path)],
                "rows": CUSTOMER_ROWS,
            },
            "nation": {
                "files": [str(nation_path)],
                "rows": len(NATIONS),
            },
            "region": {
                "files": [str(region_path)],
                "rows": len(REGIONS),
            },
            "supplier": {
                "files": [str(supplier_path)],
                "rows": SUPPLIER_ROWS,
            },
        },
    }
    with open(output_dir / "manifest.json", "w") as manifest_file:
        json.dump(manifest, manifest_file, indent=2)

    print(f"wrote {rows_written} lineitem rows across {len(file_paths)} file(s), "
          f"{total_part_rows} part rows, {partsupp_table.num_rows} partsupp rows, "
          f"{orders_written} orders rows across "
          f"{len(orders_file_paths)} file(s), {CUSTOMER_ROWS} customer rows, "
          f"{len(NATIONS)} nation rows, {len(REGIONS)} region rows, "
          f"{SUPPLIER_ROWS} supplier rows, to {output_dir}")
    print(f"manifest: {output_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
