#!/usr/bin/env python3
"""Generate a synthetic, TPC-H-*derived* `lineitem`/`part`/`orders` set as Parquet.

**This is not the official TPC-H `dbgen` tool and does not produce
certified TPC-H data.** It generates three tables (`lineitem`, `part`,
`orders`) with TPC-H's column names/types (decimal columns as DOUBLE -- see
"Deviations" below) and roughly TPC-H-shaped value distributions, sized
approximately like real TPC-H at the requested scale factor. This is
sufficient for the queries KernelLake currently supports (Q6, Q1 --
single-table scans over `lineitem`; Q19/Q14 -- a two-table
`lineitem`/`part` join; Q12 -- a two-table `orders`/`lineitem` join), but
must never be described or published as an official TPC-H benchmark
dataset.

Deviations from canonical TPC-H, documented per the spec's requirement to
record every one:
  - Only `lineitem`, `part`, and `orders` are generated. `customer`/
    `supplier`/`partsupp`/`nation`/`region` are not, since every currently
    supported TPC-H query (Q1/Q6/Q12/Q14/Q19) needs only these three
    tables.
    KernelLake does support two-table hash joins now (see docs/ROADMAP.md/
    docs/ARCHITECTURE.md's "Hash joins"), but wiring up TPC-H's queries
    that need 3+ tables (Q3 and others) is separate, not-yet-done work, not
    a generator limitation as such.
  - l_quantity/l_extendedprice/l_discount/l_tax/p_retailprice/
    o_totalprice are DOUBLE, not DECIMAL. KernelLake's GPU execution layer
    does support DECIMAL now (see docs/ARCHITECTURE.md's "DECIMAL
    support"), so this is a generator choice, not an engine limitation --
    switching would require regenerating and re-validating every existing
    TPC-H fixture, which hasn't been done.
  - Row content (prices, dates, flags, brands, containers, priorities) is
    independently sampled per row from TPC-H-plausible ranges/value sets,
    not generated by the reference `dbgen` algorithm -- so exact row
    values, and therefore exact query results, will differ from official
    TPC-H data at the same scale factor. Only the schema and approximate
    row count follow the TPC-H SF convention (`part` scales directly with
    SF, per TPC-H's own convention, unlike `lineitem`'s order-count-derived
    scaling -- see `PART_ROWS_PER_SF`; `orders` has exactly one row per
    distinct `l_orderkey` `lineitem` generated, per TPC-H's own 1:N
    orders:lineitem relationship).
  - `l_partkey` is drawn uniformly from `[1, total_part_rows]`, not
    generated by dbgen's actual part-selection distribution -- sufficient
    for every join in this table's row range to find a real `part` row (no
    dangling foreign keys), but not a claim about real TPC-H's part-access
    skew.

Usage:
    python3 tools/generate_tpch.py --scale-factor 1 --output /tmp/kernellake-tpch-sf1 \
        --format parquet --compression zstd --row-group-rows 1000000
"""

import argparse
import datetime
import json
import random
import sys
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

# Real TPC-H's lineitem row count is approximately 6,000,000 * scale factor
# (~4 line items per order, 1,500,000 * SF orders).
LINEITEM_ROWS_PER_SF = 6_000_000

# Real TPC-H's part row count scales directly with SF (unlike lineitem's
# order-count-derived scaling above).
PART_ROWS_PER_SF = 200_000

# generate_orders_batch materializes one batch's rows as Python lists before
# handing them to Arrow -- unbounded batch size means unbounded memory (this
# OOM-killed a full SF1000 run, which has ~1.5B orders rows, after 127GB
# RSS). Batch it the same way the --files loop already batches lineitem.
ORDERS_BATCH_ROWS = 5_000_000

# A representative subset of TPC-H's own p_container domain (dbgen draws
# from a larger cross product of size/container-type words) -- covers every
# size class Q19 filters on (SM/MED/LG).
CONTAINERS = [
    "SM CASE", "SM BOX", "SM PACK", "SM PKG",
    "MED BAG", "MED BOX", "MED PKG", "MED PACK",
    "LG CASE", "LG BOX", "LG PACK", "LG PKG",
]

# TPC-H's p_brand values are "Brand#" + one digit each from two
# manufacturer/brand ranges (1-5 x 1-5 -- 25 total combinations).
BRANDS = [f"Brand#{m}{b}" for m in range(1, 6) for b in range(1, 6)]

PART_TYPES = [
    "STANDARD ANODIZED TIN", "SMALL PLATED COPPER", "LARGE BRUSHED STEEL",
    "MEDIUM POLISHED BRASS", "PROMO BURNISHED NICKEL", "ECONOMY ANODIZED STEEL",
]

# TPC-H's own 5 o_orderpriority values, verbatim (Q12's WHERE/CASE branches
# match these exact strings).
ORDER_PRIORITIES = ["1-URGENT", "2-HIGH", "3-MEDIUM", "4-NOT SPECIFIED", "5-LOW"]
ORDER_STATUSES = ["O", "F", "P"]

# TPC-H's canonical order-date range is 1992-01-01 through 1998-08-02;
# ship/commit/receipt dates extend a little past that. CURRENT_DATE below
# matches dbgen's reference "current date" (1998-12-01), used for the
# returnflag/linestatus threshold (see module docstring: this threshold
# logic is an approximation of dbgen's, not a reproduction of it).
MIN_ORDER_DATE = datetime.date(1992, 1, 1)
CURRENT_DATE = datetime.date(1998, 12, 1)
RETURNFLAG_THRESHOLD = CURRENT_DATE - datetime.timedelta(days=90)

SHIP_INSTRUCTS = ["DELIVER IN PERSON", "COLLECT COD", "NONE", "TAKE BACK RETURN"]
SHIP_MODES = ["REG AIR", "AIR", "RAIL", "SHIP", "TRUCK", "MAIL", "FOB"]


def epoch_days(date: datetime.date) -> int:
    return (date - datetime.date(1970, 1, 1)).days


def generate_lineitem_batch(
    rng: random.Random, row_count: int, first_orderkey: int, total_part_rows: int
) -> pa.Table:
    orderkey = []
    partkey = []
    suppkey = []
    linenumber = []
    quantity = []
    extendedprice = []
    discount = []
    tax = []
    returnflag = []
    linestatus = []
    shipdate = []
    commitdate = []
    receiptdate = []
    shipinstruct = []
    shipmode = []
    comment = []

    current_orderkey = first_orderkey
    line_in_order = 0
    lines_for_this_order = rng.randint(1, 7)

    for _ in range(row_count):
        if line_in_order >= lines_for_this_order:
            current_orderkey += 1
            line_in_order = 0
            lines_for_this_order = rng.randint(1, 7)
        line_in_order += 1

        order_date = MIN_ORDER_DATE + datetime.timedelta(
            days=rng.randint(0, (CURRENT_DATE - MIN_ORDER_DATE).days - 151)
        )
        ship = order_date + datetime.timedelta(days=rng.randint(1, 121))
        commit = order_date + datetime.timedelta(days=rng.randint(30, 90))
        receipt = ship + datetime.timedelta(days=rng.randint(1, 30))

        qty = rng.randint(1, 50)
        unit_price = rng.uniform(1.00, 2000.00)
        line_extended = round(qty * unit_price, 2)

        if receipt <= RETURNFLAG_THRESHOLD:
            flag = rng.choice(["R", "A"])
        else:
            flag = "N"
        status = "O" if ship > RETURNFLAG_THRESHOLD else "F"

        orderkey.append(current_orderkey)
        partkey.append(rng.randint(1, total_part_rows))
        suppkey.append(rng.randint(1, 10_000))
        linenumber.append(line_in_order)
        quantity.append(float(qty))
        extendedprice.append(line_extended)
        discount.append(round(rng.uniform(0.0, 0.10), 2))
        tax.append(round(rng.uniform(0.0, 0.08), 2))
        returnflag.append(flag)
        linestatus.append(status)
        shipdate.append(epoch_days(ship))
        commitdate.append(epoch_days(commit))
        receiptdate.append(epoch_days(receipt))
        shipinstruct.append(rng.choice(SHIP_INSTRUCTS))
        shipmode.append(rng.choice(SHIP_MODES))
        comment.append("synthetic-tpch-lineitem-comment")

    schema = pa.schema(
        [
            pa.field("l_orderkey", pa.int64(), False),
            pa.field("l_partkey", pa.int64(), False),
            pa.field("l_suppkey", pa.int64(), False),
            pa.field("l_linenumber", pa.int32(), False),
            pa.field("l_quantity", pa.float64(), False),
            pa.field("l_extendedprice", pa.float64(), False),
            pa.field("l_discount", pa.float64(), False),
            pa.field("l_tax", pa.float64(), False),
            pa.field("l_returnflag", pa.utf8(), False),
            pa.field("l_linestatus", pa.utf8(), False),
            pa.field("l_shipdate", pa.date32(), False),
            pa.field("l_commitdate", pa.date32(), False),
            pa.field("l_receiptdate", pa.date32(), False),
            pa.field("l_shipinstruct", pa.utf8(), False),
            pa.field("l_shipmode", pa.utf8(), False),
            pa.field("l_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "l_orderkey": orderkey,
            "l_partkey": partkey,
            "l_suppkey": suppkey,
            "l_linenumber": linenumber,
            "l_quantity": quantity,
            "l_extendedprice": extendedprice,
            "l_discount": discount,
            "l_tax": tax,
            "l_returnflag": returnflag,
            "l_linestatus": linestatus,
            "l_shipdate": shipdate,
            "l_commitdate": commitdate,
            "l_receiptdate": receiptdate,
            "l_shipinstruct": shipinstruct,
            "l_shipmode": shipmode,
            "l_comment": comment,
        },
        schema=schema,
    )


def generate_part_table(rng: random.Random, row_count: int) -> pa.Table:
    partkey = list(range(1, row_count + 1))
    name = [f"synthetic-part-{k}" for k in partkey]
    mfgr = [f"Manufacturer#{(k % 5) + 1}" for k in partkey]
    brand = [rng.choice(BRANDS) for _ in partkey]
    ptype = [rng.choice(PART_TYPES) for _ in partkey]
    size = [rng.randint(1, 50) for _ in partkey]
    container = [rng.choice(CONTAINERS) for _ in partkey]
    retailprice = [round(rng.uniform(900.0, 2100.0), 2) for _ in partkey]
    comment = ["synthetic-tpch-part-comment" for _ in partkey]

    schema = pa.schema(
        [
            pa.field("p_partkey", pa.int64(), False),
            pa.field("p_name", pa.utf8(), False),
            pa.field("p_mfgr", pa.utf8(), False),
            pa.field("p_brand", pa.utf8(), False),
            pa.field("p_type", pa.utf8(), False),
            pa.field("p_size", pa.int32(), False),
            pa.field("p_container", pa.utf8(), False),
            pa.field("p_retailprice", pa.float64(), False),
            pa.field("p_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "p_partkey": partkey,
            "p_name": name,
            "p_mfgr": mfgr,
            "p_brand": brand,
            "p_type": ptype,
            "p_size": size,
            "p_container": container,
            "p_retailprice": retailprice,
            "p_comment": comment,
        },
        schema=schema,
    )


def generate_orders_batch(rng: random.Random, first_orderkey: int, row_count: int) -> pa.Table:
    # One row per distinct l_orderkey generate_lineitem_batch produced --
    # TPC-H's own 1:N orders:lineitem relationship -- so every lineitem row
    # has a real order to join against (no dangling foreign keys), same
    # rationale as generate_part_table's l_partkey range. Batched (see
    # ORDERS_BATCH_ROWS) rather than building all of `orders` at once, since
    # at large scale factors max_orderkey is itself in the billions.
    orderkey = list(range(first_orderkey, first_orderkey + row_count))
    custkey = [rng.randint(1, 150_000) for _ in orderkey]
    orderstatus = [rng.choice(ORDER_STATUSES) for _ in orderkey]
    totalprice = [round(rng.uniform(1000.0, 500_000.0), 2) for _ in orderkey]
    orderdate = [
        epoch_days(MIN_ORDER_DATE + datetime.timedelta(days=rng.randint(0, (CURRENT_DATE - MIN_ORDER_DATE).days)))
        for _ in orderkey
    ]
    orderpriority = [rng.choice(ORDER_PRIORITIES) for _ in orderkey]
    clerk = [f"Clerk#{rng.randint(1, 1000):09d}" for _ in orderkey]
    shippriority = [0 for _ in orderkey]
    comment = ["synthetic-tpch-orders-comment" for _ in orderkey]

    schema = pa.schema(
        [
            pa.field("o_orderkey", pa.int64(), False),
            pa.field("o_custkey", pa.int64(), False),
            pa.field("o_orderstatus", pa.utf8(), False),
            pa.field("o_totalprice", pa.float64(), False),
            pa.field("o_orderdate", pa.date32(), False),
            pa.field("o_orderpriority", pa.utf8(), False),
            pa.field("o_clerk", pa.utf8(), False),
            pa.field("o_shippriority", pa.int32(), False),
            pa.field("o_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "o_orderkey": orderkey,
            "o_custkey": custkey,
            "o_orderstatus": orderstatus,
            "o_totalprice": totalprice,
            "o_orderdate": orderdate,
            "o_orderpriority": orderpriority,
            "o_clerk": clerk,
            "o_shippriority": shippriority,
            "o_comment": comment,
        },
        schema=schema,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scale-factor", type=float, required=True)
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--format", choices=["parquet"], default="parquet")
    parser.add_argument("--compression", choices=["none", "snappy", "zstd"], default="zstd")
    parser.add_argument("--row-group-rows", type=int, default=1_000_000)
    parser.add_argument("--files", type=int, default=1, help="Number of lineitem Parquet files to write")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.scale_factor <= 0:
        parser.error("--scale-factor must be positive")
    if args.files <= 0:
        parser.error("--files must be positive")

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    total_rows = int(LINEITEM_ROWS_PER_SF * args.scale_factor)
    total_part_rows = max(1, int(PART_ROWS_PER_SF * args.scale_factor))
    rng = random.Random(args.seed)
    compression = None if args.compression == "none" else args.compression

    part_table = generate_part_table(rng, total_part_rows)
    part_path = output_dir / "part-00000.parquet"
    pq.write_table(part_table, part_path, compression=compression, row_group_size=args.row_group_rows)
    print(f"wrote {total_part_rows} rows to {part_path}")

    rows_per_file = total_rows // args.files
    extra = total_rows % args.files
    next_orderkey = 1
    file_paths = []
    rows_written = 0

    for file_index in range(args.files):
        rows_this_file = rows_per_file + (1 if file_index < extra else 0)
        if rows_this_file == 0:
            continue
        table = generate_lineitem_batch(rng, rows_this_file, next_orderkey, total_part_rows)
        next_orderkey = table.column("l_orderkey")[-1].as_py() + 1
        file_path = output_dir / f"lineitem-{file_index:05d}.parquet"
        pq.write_table(table, file_path, compression=compression, row_group_size=args.row_group_rows)
        file_paths.append(str(file_path))
        rows_written += rows_this_file
        print(f"wrote {rows_this_file} rows to {file_path}")

    max_orderkey = next_orderkey - 1
    orders_file_paths = []
    orders_written = 0
    next_orders_start = 1
    orders_file_index = 0
    while next_orders_start <= max_orderkey:
        batch_rows = min(ORDERS_BATCH_ROWS, max_orderkey - next_orders_start + 1)
        orders_table = generate_orders_batch(rng, next_orders_start, batch_rows)
        orders_path = output_dir / f"orders-{orders_file_index:05d}.parquet"
        pq.write_table(orders_table, orders_path, compression=compression, row_group_size=args.row_group_rows)
        orders_file_paths.append(str(orders_path))
        orders_written += batch_rows
        print(f"wrote {batch_rows} rows to {orders_path}")
        next_orders_start += batch_rows
        orders_file_index += 1

    manifest = {
        "benchmark": "tpch",
        "unofficial": True,
        "disclaimer": "Unofficial TPC-H-derived benchmark. Not a certified TPC result.",
        "scale_factor": args.scale_factor,
        "format": args.format,
        "compression": args.compression,
        "row_group_rows": args.row_group_rows,
        "seed": args.seed,
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "generator": "tools/generate_tpch.py (synthetic, not dbgen -- see module docstring)",
        "tables": {
            "lineitem": {
                "files": file_paths,
                "rows": rows_written,
            },
            "part": {
                "files": [str(part_path)],
                "rows": total_part_rows,
            },
            "orders": {
                "files": orders_file_paths,
                "rows": orders_written,
            },
        },
    }
    with open(output_dir / "manifest.json", "w") as manifest_file:
        json.dump(manifest, manifest_file, indent=2)

    print(f"wrote {rows_written} lineitem rows across {len(file_paths)} file(s), "
          f"{total_part_rows} part rows, {orders_written} orders rows across "
          f"{len(orders_file_paths)} file(s), to {output_dir}")
    print(f"manifest: {output_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
