#!/usr/bin/env python3
"""Generate a synthetic, TPC-H-*derived* `lineitem` table as Parquet.

**This is not the official TPC-H `dbgen` tool and does not produce
certified TPC-H data.** It generates a single table (`lineitem`) with
TPC-H's column names/types (decimal columns as DOUBLE -- see "Deviations"
below) and roughly TPC-H-shaped value distributions, sized approximately
like real TPC-H at the requested scale factor. This is sufficient for the
queries KernelLake currently supports (Q6, Q1 -- both single-table scans
over `lineitem`, no joins), but must never be described or published as an
official TPC-H benchmark dataset.

Deviations from canonical TPC-H, documented per the spec's requirement to
record every one:
  - Only `lineitem` is generated. `orders`/`customer`/`part`/`supplier`/
    `partsupp`/`nation`/`region` are not, since Q1/Q6 (the only currently
    supported TPC-H queries) are both single-table scans over `lineitem`.
    KernelLake does support two-table hash joins now (see docs/ROADMAP.md/
    docs/ARCHITECTURE.md's "Hash joins"), but wiring up TPC-H's actual
    multi-table queries (Q3/Q12/Q14) is separate, not-yet-done work, not a
    generator limitation as such.
  - l_quantity/l_extendedprice/l_discount/l_tax are DOUBLE, not DECIMAL.
    KernelLake's GPU execution layer does support DECIMAL now (see
    docs/ARCHITECTURE.md's "DECIMAL support"), so this is a generator
    choice, not an engine limitation -- switching would require
    regenerating and re-validating every existing TPC-H fixture, which
    hasn't been done.
  - Row content (prices, dates, flags) is independently sampled per row
    from TPC-H-plausible ranges, not generated by the reference `dbgen`
    algorithm -- so exact row values, and therefore exact query results,
    will differ from official TPC-H data at the same scale factor. Only
    the schema and approximate row count follow the TPC-H SF convention.

Usage:
    python3 tools/generate_tpch.py --scale-factor 1 --output /tmp/kernellake-tpch-sf1 \
        --format parquet --compression zstd --row-group-rows 1000000
"""

import argparse
import datetime
import json
import random
import sys
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

# Real TPC-H's lineitem row count is approximately 6,000,000 * scale factor
# (~4 line items per order, 1,500,000 * SF orders).
LINEITEM_ROWS_PER_SF = 6_000_000

# TPC-H's canonical order-date range is 1992-01-01 through 1998-08-02;
# ship/commit/receipt dates extend a little past that. CURRENT_DATE below
# matches dbgen's reference "current date" (1998-12-01), used for the
# returnflag/linestatus threshold (see module docstring: this threshold
# logic is an approximation of dbgen's, not a reproduction of it).
MIN_ORDER_DATE = datetime.date(1992, 1, 1)
CURRENT_DATE = datetime.date(1998, 12, 1)
RETURNFLAG_THRESHOLD = CURRENT_DATE - datetime.timedelta(days=90)

SHIP_INSTRUCTS = ["DELIVER IN PERSON", "COLLECT COD", "NONE", "TAKE BACK RETURN"]
SHIP_MODES = ["REG AIR", "AIR", "RAIL", "SHIP", "TRUCK", "MAIL", "FOB"]


def epoch_days(date: datetime.date) -> int:
    return (date - datetime.date(1970, 1, 1)).days


def generate_lineitem_batch(rng: random.Random, row_count: int, first_orderkey: int) -> pa.Table:
    orderkey = []
    partkey = []
    suppkey = []
    linenumber = []
    quantity = []
    extendedprice = []
    discount = []
    tax = []
    returnflag = []
    linestatus = []
    shipdate = []
    commitdate = []
    receiptdate = []
    shipinstruct = []
    shipmode = []
    comment = []

    current_orderkey = first_orderkey
    line_in_order = 0
    lines_for_this_order = rng.randint(1, 7)

    for _ in range(row_count):
        if line_in_order >= lines_for_this_order:
            current_orderkey += 1
            line_in_order = 0
            lines_for_this_order = rng.randint(1, 7)
        line_in_order += 1

        order_date = MIN_ORDER_DATE + datetime.timedelta(
            days=rng.randint(0, (CURRENT_DATE - MIN_ORDER_DATE).days - 151)
        )
        ship = order_date + datetime.timedelta(days=rng.randint(1, 121))
        commit = order_date + datetime.timedelta(days=rng.randint(30, 90))
        receipt = ship + datetime.timedelta(days=rng.randint(1, 30))

        qty = rng.randint(1, 50)
        unit_price = rng.uniform(1.00, 2000.00)
        line_extended = round(qty * unit_price, 2)

        if receipt <= RETURNFLAG_THRESHOLD:
            flag = rng.choice(["R", "A"])
        else:
            flag = "N"
        status = "O" if ship > RETURNFLAG_THRESHOLD else "F"

        orderkey.append(current_orderkey)
        partkey.append(rng.randint(1, 200_000))
        suppkey.append(rng.randint(1, 10_000))
        linenumber.append(line_in_order)
        quantity.append(float(qty))
        extendedprice.append(line_extended)
        discount.append(round(rng.uniform(0.0, 0.10), 2))
        tax.append(round(rng.uniform(0.0, 0.08), 2))
        returnflag.append(flag)
        linestatus.append(status)
        shipdate.append(epoch_days(ship))
        commitdate.append(epoch_days(commit))
        receiptdate.append(epoch_days(receipt))
        shipinstruct.append(rng.choice(SHIP_INSTRUCTS))
        shipmode.append(rng.choice(SHIP_MODES))
        comment.append("synthetic-tpch-lineitem-comment")

    schema = pa.schema(
        [
            pa.field("l_orderkey", pa.int64(), False),
            pa.field("l_partkey", pa.int64(), False),
            pa.field("l_suppkey", pa.int64(), False),
            pa.field("l_linenumber", pa.int32(), False),
            pa.field("l_quantity", pa.float64(), False),
            pa.field("l_extendedprice", pa.float64(), False),
            pa.field("l_discount", pa.float64(), False),
            pa.field("l_tax", pa.float64(), False),
            pa.field("l_returnflag", pa.utf8(), False),
            pa.field("l_linestatus", pa.utf8(), False),
            pa.field("l_shipdate", pa.date32(), False),
            pa.field("l_commitdate", pa.date32(), False),
            pa.field("l_receiptdate", pa.date32(), False),
            pa.field("l_shipinstruct", pa.utf8(), False),
            pa.field("l_shipmode", pa.utf8(), False),
            pa.field("l_comment", pa.utf8(), False),
        ]
    )
    return pa.table(
        {
            "l_orderkey": orderkey,
            "l_partkey": partkey,
            "l_suppkey": suppkey,
            "l_linenumber": linenumber,
            "l_quantity": quantity,
            "l_extendedprice": extendedprice,
            "l_discount": discount,
            "l_tax": tax,
            "l_returnflag": returnflag,
            "l_linestatus": linestatus,
            "l_shipdate": shipdate,
            "l_commitdate": commitdate,
            "l_receiptdate": receiptdate,
            "l_shipinstruct": shipinstruct,
            "l_shipmode": shipmode,
            "l_comment": comment,
        },
        schema=schema,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scale-factor", type=float, required=True)
    parser.add_argument("--output", required=True, help="Output directory")
    parser.add_argument("--format", choices=["parquet"], default="parquet")
    parser.add_argument("--compression", choices=["none", "snappy", "zstd"], default="zstd")
    parser.add_argument("--row-group-rows", type=int, default=1_000_000)
    parser.add_argument("--files", type=int, default=1, help="Number of lineitem Parquet files to write")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.scale_factor <= 0:
        parser.error("--scale-factor must be positive")
    if args.files <= 0:
        parser.error("--files must be positive")

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    total_rows = int(LINEITEM_ROWS_PER_SF * args.scale_factor)
    rng = random.Random(args.seed)
    compression = None if args.compression == "none" else args.compression

    rows_per_file = total_rows // args.files
    extra = total_rows % args.files
    next_orderkey = 1
    file_paths = []
    rows_written = 0

    for file_index in range(args.files):
        rows_this_file = rows_per_file + (1 if file_index < extra else 0)
        if rows_this_file == 0:
            continue
        table = generate_lineitem_batch(rng, rows_this_file, next_orderkey)
        next_orderkey = table.column("l_orderkey")[-1].as_py() + 1
        file_path = output_dir / f"lineitem-{file_index:05d}.parquet"
        pq.write_table(table, file_path, compression=compression, row_group_size=args.row_group_rows)
        file_paths.append(str(file_path))
        rows_written += rows_this_file
        print(f"wrote {rows_this_file} rows to {file_path}")

    manifest = {
        "benchmark": "tpch",
        "unofficial": True,
        "disclaimer": "Unofficial TPC-H-derived benchmark. Not a certified TPC result.",
        "scale_factor": args.scale_factor,
        "format": args.format,
        "compression": args.compression,
        "row_group_rows": args.row_group_rows,
        "seed": args.seed,
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "generator": "tools/generate_tpch.py (synthetic, not dbgen -- see module docstring)",
        "tables": {
            "lineitem": {
                "files": file_paths,
                "rows": rows_written,
            }
        },
    }
    with open(output_dir / "manifest.json", "w") as manifest_file:
        json.dump(manifest, manifest_file, indent=2)

    print(f"wrote {rows_written} lineitem rows across {len(file_paths)} file(s) to {output_dir}")
    print(f"manifest: {output_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
